@startuml
skinparam componentStyle uml2

package "Client Side (Laptop/Tablet)" #FFF2CC {
    [Browser User] as browser
    component "Frontend Engine\n(Blade + JS Fetch API)" as fe
    browser --> fe : Interaksi Klik
}

package "Server Side (Web Server)" #E1F5FE {
    component "Laravel Framework" as laravel
    component "Sanctum Middleware\n(Cek Token)" as auth
    component "Controllers\n(Logika Bisnis)" as ctrl
    
    laravel --> auth
    auth --> ctrl
}

database "Database Side" #E8F5E9 {
    [MySQL Database] as db
}

' JALUR KOMUNIKASI '
fe <--> laravel : HTTP Request / Response\n(Format JSON)
ctrl <--> db : Eloquent ORM\n(SQL Queries)
@enduml