@startuml
left to right direction
skinparam packageStyle rectangle

actor "Chef" as chef
actor "Admin" as admin

' Admin mewarisi semua kemampuan Chef
admin --|> chef

rectangle "Sistem Manajemen Stok & Resep" {
  usecase "Login" as UC_Login
  usecase "Logout" as UC_Logout
  usecase "Cek Profil (Me)" as UC_Profile
  
  usecase "Melihat Produk" as UC_ViewProduct
  usecase "Melihat Resep" as UC_ViewRecipe
  usecase "Melihat Stock Log" as UC_ViewLog
  
  usecase "Eksekusi Resep\n(Potong Otomatis)" as UC_ExecRecipe
  usecase "Potong Stok Manual" as UC_ReduceManual
  
  usecase "Manajemen User\n(CRUD & Registrasi)" as UC_ManageUser
  usecase "Manajemen Produk\n(CRUD & Restock)" as UC_ManageProduct
  usecase "Manajemen Resep\n(CRUD Resep)" as UC_ManageRecipe
}

' Relasi include autentikasi
UC_ViewProduct ..> UC_Login : <<include>>
UC_ViewRecipe ..> UC_Login : <<include>>

' Hubungan Aktor dengan Use Case
chef --> UC_Login
chef --> UC_Logout
chef --> UC_Profile
chef --> UC_ViewProduct
chef --> UC_ViewRecipe
chef --> UC_ViewLog
chef --> UC_ExecRecipe
chef --> UC_ReduceManual

admin --> UC_ManageUser
admin --> UC_ManageProduct
admin --> UC_ManageRecipe
@endum